import { Component, computed, isDevMode, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HlmButtonImports } from '@spartan-ng/helm/button';
import { HlmEmptyImports } from '@spartan-ng/helm/empty';
import { HlmInputImports } from '@spartan-ng/helm/input';
import { HlmLabelImports } from '@spartan-ng/helm/label';
import { HlmSwitchImports } from '@spartan-ng/helm/switch';
import {
	AccessibilityIcon,
	ActivityIcon,
	AirplayIcon,
	AlarmClockCheckIcon,
	AlarmClockIcon,
	AlarmClockOffIcon,
	AlignHorizontalSpaceAroundIcon,
	AlignVerticalSpaceAroundIcon,
	// AnvilIcon,
	ArchiveIcon,
	ArrowBigDownDashIcon,
	ArrowBigDownIcon,
	ArrowBigLeftDashIcon,
	ArrowBigLeftIcon,
	ArrowBigRightDashIcon,
	ArrowBigRightIcon,
	ArrowBigUpDashIcon,
	ArrowBigUpIcon,
	ArrowDown01Icon,
	ArrowDown10Icon,
	ArrowDownAZIcon,
	ArrowDownLeftIcon,
	ArrowDownRightIcon,
	ArrowDownZAIcon,
	ArrowDownIcon,
	ArrowLeftRightIcon,
	ArrowLeftIcon,
	ArrowRightLeftIcon,
	ArrowRightIcon,
	ArrowUp01Icon,
	ArrowUp10Icon,
	ArrowUpAZIcon,
	ArrowUpLeftIcon,
	ArrowUpRightIcon,
	ArrowUpZAIcon,
	ArrowUpIcon,
	AudioLinesIcon,
	AwardIcon,
	AxeIcon,
	Axis3dIcon,
	BadgeAlertIcon,
	BadgeCheckIcon,
	BadgeQuestionMarkIcon,
	BatteryChargingIcon,
	BatteryFullIcon,
	BatteryLowIcon,
	BatteryMediumIcon,
	BatteryWarningIcon,
	BatteryIcon,
	BeanOffIcon,
	BeerOffIcon,
	BellOffIcon,
	BellRingIcon,
	BellIcon,
	BetweenHorizontalEndIcon,
	BetweenHorizontalStartIcon,
	BetweenVerticalEndIcon,
	BetweenVerticalStartIcon,
	BinaryIcon,
	BlendIcon,
	BlocksIcon,
	BluetoothOffIcon,
	BoldIcon,
	BoltIcon,
	BoneIcon,
	BookAIcon,
	BookAudioIcon,
	BookCheckIcon,
	BookDashedIcon,
	BookDownIcon,
	BookHeadphonesIcon,
	BookHeartIcon,
	BookImageIcon,
	BookKeyIcon,
	BookLockIcon,
	BookMarkedIcon,
	BookMinusIcon,
	BookOpenCheckIcon,
	BookOpenTextIcon,
	BookPlusIcon,
	BookTextIcon,
	BookTypeIcon,
	BookUp2Icon,
	BookUpIcon,
	BookUserIcon,
	BookXIcon,
	BookIcon,
	BookmarkCheckIcon,
	BookmarkMinusIcon,
	BookmarkPlusIcon,
	BookmarkXIcon,
	BookmarkIcon,
	BotOffIcon,
	BotIcon,
	BoxesIcon,
	BrainCogIcon,
	BriefcaseBusinessIcon,
	BriefcaseConveyorBeltIcon,
	BriefcaseMedicalIcon,
	BriefcaseIcon,
	BrushCleaningIcon,
	BrushIcon,
	BugOffIcon,
	CalendarCheck2Icon,
	CalendarCheckIcon,
	CalendarCogIcon,
	// CalendarDaysIcon,
	CalendarOffIcon,
	CalendarSyncIcon,
	CameraOffIcon,
	CandyOffIcon,
	CaptionsOffIcon,
	CastIcon,
	CctvIcon,
	ChartBarDecreasingIcon,
	ChartBarIncreasingIcon,
	ChartBarIcon,
	ChartColumnDecreasingIcon,
	ChartColumnIncreasingIcon,
	ChartColumnIcon,
	ChartGanttIcon,
	ChartLineIcon,
	ChartNoAxesColumnDecreasingIcon,
	ChartNoAxesColumnIncreasingIcon,
	ChartNoAxesColumnIcon,
	ChartNoAxesCombinedIcon,
	ChartNoAxesGanttIcon,
	ChartPieIcon,
	// ChartScatterIcon,
	ChartSplineIcon,
	CheckCheckIcon,
	CheckIcon,
	CherryIcon,
	ChevronDownIcon,
	ChevronLeftIcon,
	ChevronRightIcon,
	ChevronUpIcon,
	ChevronsDownUpIcon,
	ChevronsDownIcon,
	ChevronsLeftRightIcon,
	ChevronsLeftIcon,
	ChevronsRightLeftIcon,
	ChevronsRightIcon,
	ChevronsUpDownIcon,
	ChevronsUpIcon,
	CigaretteOffIcon,
	CircleAlertIcon,
	CircleArrowDownIcon,
	CircleArrowLeftIcon,
	CircleArrowOutDownLeftIcon,
	CircleArrowOutDownRightIcon,
	CircleArrowOutUpLeftIcon,
	CircleArrowOutUpRightIcon,
	CircleArrowRightIcon,
	CircleArrowUpIcon,
	CircleCheckBigIcon,
	CircleCheckIcon,
	CircleChevronDownIcon,
	CircleChevronLeftIcon,
	CircleChevronRightIcon,
	CircleChevronUpIcon,
	CircleOffIcon,
	CircleParkingOffIcon,
	CirclePlusIcon,
	CircleQuestionMarkIcon,
	ClapperboardIcon,
	ClipboardCheckIcon,
	ClipboardListIcon,
	ClipboardPenLineIcon,
	ClipboardPenIcon,
	ClipboardIcon,
	Clock1Icon,
	Clock10Icon,
	Clock11Icon,
	Clock12Icon,
	Clock2Icon,
	Clock3Icon,
	Clock4Icon,
	Clock5Icon,
	Clock6Icon,
	Clock7Icon,
	Clock8Icon,
	Clock9Icon,
	ClockIcon,
	CloudCogIcon,
	CloudDownloadIcon,
	CloudMoonIcon,
	CloudOffIcon,
	CloudUploadIcon,
	CogIcon,
	CompassIcon,
	ContrastIcon,
	CopyCheckIcon,
	CopyIcon,
	CpuIcon,
	CropIcon,
	DiamondPlusIcon,
	Dice1Icon,
	Dice2Icon,
	Dice3Icon,
	Dice4Icon,
	Dice5Icon,
	Dice6Icon,
	DiffIcon,
	DnaOffIcon,
	DownloadIcon,
	DropletOffIcon,
	DrumIcon,
	EarOffIcon,
	EclipseIcon,
	EggOffIcon,
	ExpandIcon,
	EyeOffIcon,
	FileChartColumnIncreasingIcon,
	FileChartColumnIcon,
	FileChartLineIcon,
	FileCheckCornerIcon,
	FileCheckIcon,
	FileDownIcon,
	FileMinusIcon,
	FilePenLineIcon,
	FilePenIcon,
	FilePlusIcon,
	FileQuestionMarkIcon,
	FileSlidersIcon,
	FileStackIcon,
	FileTerminalIcon,
	FileUpIcon,
	FishOffIcon,
	FlagOffIcon,
	FlashlightOffIcon,
	FlaskConicalOffIcon,
	FolderCheckIcon,
	FolderCogIcon,
	FolderDownIcon,
	FolderKanbanIcon,
	FolderPenIcon,
	FolderPlusIcon,
	FolderSyncIcon,
	FolderUpIcon,
	FrameIcon,
	GalleryHorizontalEndIcon,
	GalleryHorizontalIcon,
	// GalleryThumbnailsIcon,
	GalleryVerticalEndIcon,
	GalleryVerticalIcon,
	GaugeIcon,
	GavelIcon,
	Grid2x2CheckIcon,
	// GripHorizontalIcon,
	// GripVerticalIcon,
	// GripIcon,
	HammerIcon,
	HandCoinsIcon,
	HandHeartIcon,
	HardDriveDownloadIcon,
	HardDriveUploadIcon,
	HeadphoneOffIcon,
	HeartOffIcon,
	HeartIcon,
	HistoryIcon,
	HopOffIcon,
	HouseWifiIcon,
	HouseIcon,
	ImageDownIcon,
	ImageOffIcon,
	ImageUpIcon,
	ImagesIcon,
	InfinityIcon,
	KanbanIcon,
	KeyRoundIcon,
	KeySquareIcon,
	KeyIcon,
	KeyboardOffIcon,
	// KeyboardIcon,
	LandmarkIcon,
	LayersIcon,
	LayoutDashboardIcon,
	LayoutGridIcon,
	LayoutPanelLeftIcon,
	LayoutPanelTopIcon,
	LayoutTemplateIcon,
	LightbulbOffIcon,
	LightbulbIcon,
	Link2OffIcon,
	ListCheckIcon,
	ListChecksIcon,
	ListRestartIcon,
	ListTodoIcon,
	LoaderPinwheelIcon,
	LocateOffIcon,
	LogOutIcon,
	MailCheckIcon,
	MapPinCheckInsideIcon,
	MapPinCheckIcon,
	MapPinOffIcon,
	Maximize2Icon,
	MaximizeIcon,
	MegaphoneOffIcon,
	MessageCircleMoreIcon,
	MessageCircleOffIcon,
	MessageCircleQuestionMarkIcon,
	MessageCircleWarningIcon,
	MessageCircleIcon,
	MessageSquareMoreIcon,
	MessageSquareOffIcon,
	MessageSquareIcon,
	MicOffIcon,
	MilkOffIcon,
	Minimize2Icon,
	MinimizeIcon,
	MinusIcon,
	MonitorCheckIcon,
	MonitorCogIcon,
	MonitorDownIcon,
	MonitorOffIcon,
	MonitorUpIcon,
	MouseOffIcon,
	MousePointer2Icon,
	MousePointerIcon,
	MoveDiagonal2Icon,
	MoveDiagonalIcon,
	MoveDownLeftIcon,
	MoveDownRightIcon,
	MoveDownIcon,
	MoveHorizontalIcon,
	MoveLeftIcon,
	MoveRightIcon,
	MoveUpLeftIcon,
	MoveUpRightIcon,
	MoveUpIcon,
	MoveVerticalIcon,
	Navigation2OffIcon,
	NavigationOffIcon,
	NfcIcon,
	NotebookPenIcon,
	NutOffIcon,
	OctagonAlertIcon,
	OrbitIcon,
	PackageCheckIcon,
	PaintbrushIcon,
	PanelBottomCloseIcon,
	PanelBottomOpenIcon,
	PanelLeftCloseIcon,
	PanelLeftOpenIcon,
	PanelRightCloseIcon,
	PanelRightOpenIcon,
	PanelTopCloseIcon,
	PanelTopOpenIcon,
	PaperclipIcon,
	PenLineIcon,
	PenOffIcon,
	PenIcon,
	PencilLineIcon,
	PencilOffIcon,
	PencilIcon,
	PhoneOffIcon,
	PickaxeIcon,
	PinOffIcon,
	// PlaneIcon,
	PlayIcon,
	PlusIcon,
	PointerOffIcon,
	PowerOffIcon,
	PrinterCheckIcon,
	RabbitIcon,
	RadarIcon,
	RadioTowerIcon,
	RadioIcon,
	RainbowIcon,
	RedoDotIcon,
	RedoIcon,
	RefreshCcwDotIcon,
	RefreshCcwIcon,
	RefreshCwOffIcon,
	RefreshCwIcon,
	RocketIcon,
	RockingChairIcon,
	RotateCcwKeyIcon,
	RotateCcwIcon,
	RotateCwIcon,
	RouteOffIcon,
	RouteIcon,
	RssIcon,
	SaveOffIcon,
	ScanTextIcon,
	ScissorsIcon,
	SearchCheckIcon,
	SearchIcon,
	SendHorizontalIcon,
	SendIcon,
	ServerCogIcon,
	ServerOffIcon,
	SettingsIcon,
	ShieldAlertIcon,
	ShieldCheckIcon,
	ShieldOffIcon,
	ShieldPlusIcon,
	ShieldQuestionMarkIcon,
	ShipWheelIcon,
	ShipIcon,
	ShoppingCartIcon,
	ShovelIcon,
	// ShowerHeadIcon,
	ShrinkIcon,
	SignalHighIcon,
	SignalLowIcon,
	SignalMediumIcon,
	SignalZeroIcon,
	SignalIcon,
	SignatureIcon,
	SlidersHorizontalIcon,
	SlidersVerticalIcon,
	SmartphoneNfcIcon,
	SnowflakeIcon,
	SparkleIcon,
	SparklesIcon,
	SpeechIcon,
	SpellCheckIcon,
	SquareArrowDownLeftIcon,
	SquareArrowDownRightIcon,
	SquareArrowDownIcon,
	SquareArrowLeftIcon,
	SquareArrowOutDownLeftIcon,
	SquareArrowOutDownRightIcon,
	SquareArrowOutUpLeftIcon,
	SquareArrowOutUpRightIcon,
	SquareArrowRightIcon,
	SquareArrowUpLeftIcon,
	SquareArrowUpRightIcon,
	SquareArrowUpIcon,
	SquareChartGanttIcon,
	SquareCheckBigIcon,
	SquareCheckIcon,
	SquareChevronDownIcon,
	SquareChevronLeftIcon,
	SquareChevronRightIcon,
	SquareChevronUpIcon,
	SquareDashedKanbanIcon,
	SquareKanbanIcon,
	SquareParkingOffIcon,
	SquarePenIcon,
	SquarePlusIcon,
	SquareScissorsIcon,
	SquareStackIcon,
	SquareTerminalIcon,
	StarOffIcon,
	StarIcon,
	// SunIcon,
	SwordIcon,
	TagIcon,
	TelescopeIcon,
	TerminalIcon,
	TextAlignCenterIcon,
	TextCursorInputIcon,
	TextCursorIcon,
	TextSearchIcon,
	ThermometerIcon,
	ThumbsDownIcon,
	ThumbsUpIcon,
	TicketCheckIcon,
	TimerOffIcon,
	TimerIcon,
	ToggleLeftIcon,
	ToggleRightIcon,
	TornadoIcon,
	TouchpadOffIcon,
	Trash2Icon,
	TrashIcon,
	TriangleAlertIcon,
	UmbrellaOffIcon,
	UndoDotIcon,
	UndoIcon,
	UnfoldHorizontalIcon,
	UnfoldVerticalIcon,
	UnplugIcon,
	UploadIcon,
	UserCheckIcon,
	UserCogIcon,
	UserPenIcon,
	UserRoundCheckIcon,
	UserRoundCogIcon,
	UserRoundPenIcon,
	UserRoundIcon,
	UserIcon,
	VibrateOffIcon,
	VibrateIcon,
	VideoOffIcon,
	VolumeOffIcon,
	VoteIcon,
	WavesIcon,
	WebhookOffIcon,
	WheatOffIcon,
	WifiHighIcon,
	WifiLowIcon,
	WifiOffIcon,
	WifiPenIcon,
	WifiZeroIcon,
	WifiIcon,
	WineOffIcon,
	XIcon,
	ZapOffIcon,
} from 'ng-animated-icons';
import { IconCard } from './icon-card';
import type { IconItem } from './icon-item.type';

@Component({
	selector: 'docs-explorer',
	template: `
		<div class="relative max-w-sm">
			<input class="peer pe-18" [(ngModel)]="searchTerm" hlmInput placeholder="Search icons..." />
			<div
				class="text-muted-foreground/80 pointer-events-none absolute inset-y-0 end-0 flex items-center justify-center pe-3 text-xs peer-disabled:opacity-50"
			>
				{{ iconCountMessage() }}
			</div>
		</div>

		<!-- eslint-disable-next-line @angular-eslint/template/label-has-associated-control -->
		@if (isDevMode) {
			<label class="flex items-center" hlmLabel>
				<hlm-switch class="mr-2" [(checked)]="includeWip" />
				@if (includeWip()) {
					Including WIP icons
				} @else {
					Excluding WIP icons
				}
			</label>
		}

		@let icons = filteredIcons();

		@if (icons.length === 0) {
			<div class="bg-background my-4" hlmEmpty>
				<div hlmEmptyHeader>
					<div hlmEmptyTitle>No icons matched</div>
					<div hlmEmptyDescription>
						There are no icons for <strong>"{{ cleanSearchTerm() }}"</strong>. Please try searching by other names.
					</div>
				</div>
				<div hlmEmptyContent>
					<div class="flex gap-2">
						<button (click)="searchTerm.set('')" hlmBtn>Clear Search</button>
					</div>
				</div>
			</div>
		} @else {
			<div class="grid w-full grid-cols-[repeat(auto-fill,minmax(200px,1fr))] gap-1 py-2">
				@for (icon of icons; track icon.name) {
					<docs-icon-card [class.hidden]="!includeWip() && icon.wip" [icon]="icon" />
				}
			</div>
		}
	`,
	host: {
		class: 'flex flex-col items-center gap-4 min-h-96',
	},
	imports: [
		FormsModule,
		HlmButtonImports,
		HlmEmptyImports,
		HlmInputImports,
		HlmLabelImports,
		HlmSwitchImports,
		IconCard,
	],
})
export class Explorer {
	readonly isDevMode = isDevMode();

	searchTerm = signal('');
	includeWip = signal(this.isDevMode);

	icons = signal<IconItem[]>([
		{ name: 'accessibility', component: AccessibilityIcon },
		{ name: 'activity', component: ActivityIcon },
		{ name: 'airplay', component: AirplayIcon },
		{ name: 'alarm-clock-check', component: AlarmClockCheckIcon },
		{ name: 'alarm-clock-off', component: AlarmClockOffIcon },
		{ name: 'alarm-clock', component: AlarmClockIcon },
		{ name: 'align-horizontal-space-around', component: AlignHorizontalSpaceAroundIcon },
		{ name: 'align-vertical-space-around', component: AlignVerticalSpaceAroundIcon },
		// { wip: true, name: 'anvil', component: AnvilIcon },
		{ name: 'archive', component: ArchiveIcon },
		{ name: 'arrow-big-down-dash', component: ArrowBigDownDashIcon },
		// { wip: true, name: 'arrow-big-down', component: ArrowBigDownIcon },
		// { wip: true, name: 'arrow-big-left-dash', component: ArrowBigLeftDashIcon },
		// { wip: true, name: 'arrow-big-left', component: ArrowBigLeftIcon },
		// { wip: true, name: 'arrow-big-right-dash', component: ArrowBigRightDashIcon },
		// { wip: true, name: 'arrow-big-right', component: ArrowBigRightIcon },
		// { wip: true, name: 'arrow-big-up-dash', component: ArrowBigUpDashIcon },
		// { wip: true, name: 'arrow-big-up', component: ArrowBigUpIcon },
		// { wip: true, name: 'arrow-down-0-1', component: ArrowDown01Icon },
		// { wip: true, name: 'arrow-down-1-0', component: ArrowDown10Icon },
		// { wip: true, name: 'arrow-down-a-z', component: ArrowDownAZIcon },
		// { wip: true, name: 'arrow-down-left', component: ArrowDownLeftIcon },
		// { wip: true, name: 'arrow-down-right', component: ArrowDownRightIcon },
		// { wip: true, name: 'arrow-down-z-a', component: ArrowDownZAIcon },
		// { wip: true, name: 'arrow-down', component: ArrowDownIcon },
		// { wip: true, name: 'arrow-left-right', component: ArrowLeftRightIcon },
		// { wip: true, name: 'arrow-left', component: ArrowLeftIcon },
		// { wip: true, name: 'arrow-right-left', component: ArrowRightLeftIcon },
		// { wip: true, name: 'arrow-right', component: ArrowRightIcon },
		// { wip: true, name: 'arrow-up-0-1', component: ArrowUp01Icon },
		// { wip: true, name: 'arrow-up-1-0', component: ArrowUp10Icon },
		// { wip: true, name: 'arrow-up-a-z', component: ArrowUpAZIcon },
		// { wip: true, name: 'arrow-up-left', component: ArrowUpLeftIcon },
		// { wip: true, name: 'arrow-up-right', component: ArrowUpRightIcon },
		// { wip: true, name: 'arrow-up-z-a', component: ArrowUpZAIcon },
		// { wip: true, name: 'arrow-up', component: ArrowUpIcon },
		// { wip: true, name: 'audio-lines', component: AudioLinesIcon },
		{ name: 'award', component: AwardIcon },
		// { wip: true, name: 'axe', component: AxeIcon },
		// { wip: true, name: 'axis-3d', component: Axis3dIcon },
		// { wip: true, name: 'badge-alert', component: BadgeAlertIcon },
		// { wip: true, name: 'badge-check', component: BadgeCheckIcon },
		// { wip: true, name: 'badge-question-mark', component: BadgeQuestionMarkIcon },
		// { wip: true, name: 'battery-charging', component: BatteryChargingIcon },
		// { wip: true, name: 'battery-full', component: BatteryFullIcon },
		// { wip: true, name: 'battery-low', component: BatteryLowIcon },
		// { wip: true, name: 'battery-medium', component: BatteryMediumIcon },
		// { wip: true, name: 'battery-warning', component: BatteryWarningIcon },
		// { wip: true, name: 'battery', component: BatteryIcon },
		// { wip: true, name: 'bean-off', component: BeanOffIcon },
		// { wip: true, name: 'beer-off', component: BeerOffIcon },
		// { wip: true, name: 'bell-off', component: BellOffIcon },
		// { wip: true, name: 'bell-ring', component: BellRingIcon },
		// { wip: true, name: 'bell', component: BellIcon },
		// { wip: true, name: 'between-horizontal-end', component: BetweenHorizontalEndIcon },
		// { wip: true, name: 'between-horizontal-start', component: BetweenHorizontalStartIcon },
		// { wip: true, name: 'between-vertical-end', component: BetweenVerticalEndIcon },
		// { wip: true, name: 'between-vertical-start', component: BetweenVerticalStartIcon },
		// { wip: true, name: 'binary', component: BinaryIcon },
		// { wip: true, name: 'blend', component: BlendIcon },
		// { wip: true, name: 'blocks', component: BlocksIcon },
		// { wip: true, name: 'bluetooth-off', component: BluetoothOffIcon },
		// { wip: true, name: 'bold', component: BoldIcon },
		// { wip: true, name: 'bolt', component: BoltIcon },
		// { wip: true, name: 'bone', component: BoneIcon },
		// { wip: true, name: 'book-a', component: BookAIcon },
		// { wip: true, name: 'book-audio', component: BookAudioIcon },
		// { wip: true, name: 'book-check', component: BookCheckIcon },
		// { wip: true, name: 'book-dashed', component: BookDashedIcon },
		// { wip: true, name: 'book-down', component: BookDownIcon },
		// { wip: true, name: 'book-headphones', component: BookHeadphonesIcon },
		// { wip: true, name: 'book-heart', component: BookHeartIcon },
		// { wip: true, name: 'book-image', component: BookImageIcon },
		// { wip: true, name: 'book-key', component: BookKeyIcon },
		// { wip: true, name: 'book-lock', component: BookLockIcon },
		// { wip: true, name: 'book-marked', component: BookMarkedIcon },
		// { wip: true, name: 'book-minus', component: BookMinusIcon },
		// { wip: true, name: 'book-open-check', component: BookOpenCheckIcon },
		// { wip: true, name: 'book-open-text', component: BookOpenTextIcon },
		// { wip: true, name: 'book-plus', component: BookPlusIcon },
		// { wip: true, name: 'book-text', component: BookTextIcon },
		// { wip: true, name: 'book-type', component: BookTypeIcon },
		// { wip: true, name: 'book-up-2', component: BookUp2Icon },
		// { wip: true, name: 'book-up', component: BookUpIcon },
		// { wip: true, name: 'book-user', component: BookUserIcon },
		// { wip: true, name: 'book-x', component: BookXIcon },
		// { wip: true, name: 'book', component: BookIcon },
		{ name: 'bookmark-check', component: BookmarkCheckIcon },
		{ name: 'bookmark-minus', component: BookmarkMinusIcon },
		{ name: 'bookmark-plus', component: BookmarkPlusIcon },
		{ name: 'bookmark-x', component: BookmarkXIcon },
		{ name: 'bookmark', component: BookmarkIcon },
		// { wip: true, name: 'bot-off', component: BotOffIcon },
		// { wip: true, name: 'bot', component: BotIcon },
		{ name: 'boxes', component: BoxesIcon },
		// { wip: true, name: 'brain-cog', component: BrainCogIcon },
		{ name: 'briefcase-business', component: BriefcaseBusinessIcon },
		{ name: 'briefcase-conveyor-belt', component: BriefcaseConveyorBeltIcon },
		{ name: 'briefcase-medical', component: BriefcaseMedicalIcon },
		{ name: 'briefcase', component: BriefcaseIcon },
		{ name: 'brush-cleaning', component: BrushCleaningIcon },
		{ name: 'brush', component: BrushIcon },
		{ name: 'bug-off', component: BugOffIcon },
		{ name: 'calendar-check-2', component: CalendarCheck2Icon },
		{ name: 'calendar-check', component: CalendarCheckIcon },
		{ name: 'calendar-cog', component: CalendarCogIcon },
		// // { wip: true, name: 'calendar-days', component: CalendarDaysIcon },
		{ name: 'calendar-off', component: CalendarOffIcon },
		{ name: 'calendar-sync', component: CalendarSyncIcon },
		{ name: 'camera-off', component: CameraOffIcon },
		{ name: 'candy-off', component: CandyOffIcon },
		{ name: 'captions-off', component: CaptionsOffIcon },
		{ name: 'cast', component: CastIcon },
		{ name: 'cctv', component: CctvIcon },
		// { wip: true, name: 'chart-bar-decreasing', component: ChartBarDecreasingIcon },
		// { wip: true, name: 'chart-bar-increasing', component: ChartBarIncreasingIcon },
		// { wip: true, name: 'chart-bar', component: ChartBarIcon },
		// { wip: true, name: 'chart-column-decreasing', component: ChartColumnDecreasingIcon },
		// { wip: true, name: 'chart-column-increasing', component: ChartColumnIncreasingIcon },
		// { wip: true, name: 'chart-column', component: ChartColumnIcon },
		// { wip: true, name: 'chart-gantt', component: ChartGanttIcon },
		// { wip: true, name: 'chart-line', component: ChartLineIcon },
		// { wip: true, name: 'chart-no-axes-column-decreasing', component: ChartNoAxesColumnDecreasingIcon },
		// { wip: true, name: 'chart-no-axes-column-increasing', component: ChartNoAxesColumnIncreasingIcon },
		// { wip: true, name: 'chart-no-axes-column', component: ChartNoAxesColumnIcon },
		// { wip: true, name: 'chart-no-axes-combined', component: ChartNoAxesCombinedIcon },
		// { wip: true, name: 'chart-no-axes-gantt', component: ChartNoAxesGanttIcon },
		// { wip: true, name: 'chart-pie', component: ChartPieIcon },
		// // { wip: true, name: 'chart-scatter', component: ChartScatterIcon },
		// { wip: true, name: 'chart-spline', component: ChartSplineIcon },
		// { wip: true, name: 'check-check', component: CheckCheckIcon },
		// { wip: true, name: 'check', component: CheckIcon },
		// { wip: true, name: 'cherry', component: CherryIcon },
		{ name: 'chevron-down', component: ChevronDownIcon },
		{ name: 'chevron-left', component: ChevronLeftIcon },
		{ name: 'chevron-right', component: ChevronRightIcon },
		{ name: 'chevron-up', component: ChevronUpIcon },
		{ name: 'chevrons-down-up', component: ChevronsDownUpIcon },
		{ name: 'chevrons-down', component: ChevronsDownIcon },
		{ name: 'chevrons-left-right', component: ChevronsLeftRightIcon },
		{ name: 'chevrons-left', component: ChevronsLeftIcon },
		{ name: 'chevrons-right-left', component: ChevronsRightLeftIcon },
		{ name: 'chevrons-right', component: ChevronsRightIcon },
		{ name: 'chevrons-up-down', component: ChevronsUpDownIcon },
		{ name: 'chevrons-up', component: ChevronsUpIcon },
		// { wip: true, name: 'cigarette-off', component: CigaretteOffIcon },
		// { wip: true, name: 'circle-alert', component: CircleAlertIcon },
		// { wip: true, name: 'circle-arrow-down', component: CircleArrowDownIcon },
		// { wip: true, name: 'circle-arrow-left', component: CircleArrowLeftIcon },
		// { wip: true, name: 'circle-arrow-out-down-left', component: CircleArrowOutDownLeftIcon },
		// { wip: true, name: 'circle-arrow-out-down-right', component: CircleArrowOutDownRightIcon },
		// { wip: true, name: 'circle-arrow-out-up-left', component: CircleArrowOutUpLeftIcon },
		// { wip: true, name: 'circle-arrow-out-up-right', component: CircleArrowOutUpRightIcon },
		// { wip: true, name: 'circle-arrow-right', component: CircleArrowRightIcon },
		// { wip: true, name: 'circle-arrow-up', component: CircleArrowUpIcon },
		// { wip: true, name: 'circle-check-big', component: CircleCheckBigIcon },
		// { wip: true, name: 'circle-check', component: CircleCheckIcon },
		// { wip: true, name: 'circle-chevron-down', component: CircleChevronDownIcon },
		// { wip: true, name: 'circle-chevron-left', component: CircleChevronLeftIcon },
		// { wip: true, name: 'circle-chevron-right', component: CircleChevronRightIcon },
		// { wip: true, name: 'circle-chevron-up', component: CircleChevronUpIcon },
		// { wip: true, name: 'circle-off', component: CircleOffIcon },
		// { wip: true, name: 'circle-parking-off', component: CircleParkingOffIcon },
		// { wip: true, name: 'circle-plus', component: CirclePlusIcon },
		{ name: 'circle-question-mark', component: CircleQuestionMarkIcon },
		{ name: 'clapperboard', component: ClapperboardIcon },
		{ name: 'clipboard-check', component: ClipboardCheckIcon },
		{ name: 'clipboard-list', component: ClipboardListIcon },
		{ name: 'clipboard-pen-line', component: ClipboardPenLineIcon },
		{ name: 'clipboard-pen', component: ClipboardPenIcon },
		{ name: 'clipboard', component: ClipboardIcon },
		{ name: 'clock', component: ClockIcon },
		{ name: 'clock-1', component: Clock1Icon },
		{ name: 'clock-2', component: Clock2Icon },
		{ name: 'clock-3', component: Clock3Icon },
		{ name: 'clock-4', component: Clock4Icon },
		{ name: 'clock-5', component: Clock5Icon },
		{ name: 'clock-6', component: Clock6Icon },
		{ name: 'clock-7', component: Clock7Icon },
		{ name: 'clock-8', component: Clock8Icon },
		{ name: 'clock-9', component: Clock9Icon },
		{ name: 'clock-10', component: Clock10Icon },
		{ name: 'clock-11', component: Clock11Icon },
		{ name: 'clock-12', component: Clock12Icon },
		{ name: 'cloud-cog', component: CloudCogIcon },
		{ name: 'cloud-download', component: CloudDownloadIcon },
		{ name: 'cloud-moon', component: CloudMoonIcon },
		{ name: 'cloud-off', component: CloudOffIcon },
		{ name: 'cloud-upload', component: CloudUploadIcon },
		// { wip: true, name: 'cog', component: CogIcon },
		// { wip: true, name: 'compass', component: CompassIcon },
		// { wip: true, name: 'contrast', component: ContrastIcon },
		{ name: 'copy-check', component: CopyCheckIcon },
		// { wip: true, name: 'copy', component: CopyIcon },
		// { wip: true, name: 'cpu', component: CpuIcon },
		// { wip: true, name: 'crop', component: CropIcon },
		// { wip: true, name: 'diamond-plus', component: DiamondPlusIcon },
		// { wip: true, name: 'dice-1', component: Dice1Icon },
		// { wip: true, name: 'dice-2', component: Dice2Icon },
		// { wip: true, name: 'dice-3', component: Dice3Icon },
		// { wip: true, name: 'dice-4', component: Dice4Icon },
		// { wip: true, name: 'dice-5', component: Dice5Icon },
		// { wip: true, name: 'dice-6', component: Dice6Icon },
		// { wip: true, name: 'diff', component: DiffIcon },
		// { wip: true, name: 'dna-off', component: DnaOffIcon },
		// { wip: true, name: 'download', component: DownloadIcon },
		// { wip: true, name: 'droplet-off', component: DropletOffIcon },
		// { wip: true, name: 'drum', component: DrumIcon },
		// { wip: true, name: 'ear-off', component: EarOffIcon },
		// { wip: true, name: 'eclipse', component: EclipseIcon },
		// { wip: true, name: 'egg-off', component: EggOffIcon },
		// { wip: true, name: 'expand', component: ExpandIcon },
		// { wip: true, name: 'eye-off', component: EyeOffIcon },
		// { wip: true, name: 'file-chart-column-increasing', component: FileChartColumnIncreasingIcon },
		// { wip: true, name: 'file-chart-column', component: FileChartColumnIcon },
		// { wip: true, name: 'file-chart-line', component: FileChartLineIcon },
		// { wip: true, name: 'file-check-corner', component: FileCheckCornerIcon },
		// { wip: true, name: 'file-check', component: FileCheckIcon },
		// { wip: true, name: 'file-down', component: FileDownIcon },
		// { wip: true, name: 'file-minus', component: FileMinusIcon },
		// { wip: true, name: 'file-pen-line', component: FilePenLineIcon },
		// { wip: true, name: 'file-pen', component: FilePenIcon },
		// { wip: true, name: 'file-plus', component: FilePlusIcon },
		// { wip: true, name: 'file-question-mark', component: FileQuestionMarkIcon },
		// { wip: true, name: 'file-sliders', component: FileSlidersIcon },
		// { wip: true, name: 'file-stack', component: FileStackIcon },
		// { wip: true, name: 'file-terminal', component: FileTerminalIcon },
		// { wip: true, name: 'file-up', component: FileUpIcon },
		// { wip: true, name: 'fish-off', component: FishOffIcon },
		// { wip: true, name: 'flag-off', component: FlagOffIcon },
		// { wip: true, name: 'flashlight-off', component: FlashlightOffIcon },
		// { wip: true, name: 'flask-conical-off', component: FlaskConicalOffIcon },
		// { wip: true, name: 'folder-check', component: FolderCheckIcon },
		// { wip: true, name: 'folder-cog', component: FolderCogIcon },
		// { wip: true, name: 'folder-down', component: FolderDownIcon },
		// { wip: true, name: 'folder-kanban', component: FolderKanbanIcon },
		// { wip: true, name: 'folder-pen', component: FolderPenIcon },
		// { wip: true, name: 'folder-plus', component: FolderPlusIcon },
		// { wip: true, name: 'folder-sync', component: FolderSyncIcon },
		// { wip: true, name: 'folder-up', component: FolderUpIcon },
		// { wip: true, name: 'frame', component: FrameIcon },
		// { wip: true, name: 'gallery-horizontal-end', component: GalleryHorizontalEndIcon },
		// { wip: true, name: 'gallery-horizontal', component: GalleryHorizontalIcon },
		// // { wip: true, name: 'gallery-thumbnails', component: GalleryThumbnailsIcon },
		// { wip: true, name: 'gallery-vertical-end', component: GalleryVerticalEndIcon },
		// { wip: true, name: 'gallery-vertical', component: GalleryVerticalIcon },
		// { wip: true, name: 'gauge', component: GaugeIcon },
		// { wip: true, name: 'gavel', component: GavelIcon },
		// { wip: true, name: 'grid-2x2-check', component: Grid2x2CheckIcon },
		// // { wip: true, name: 'grip-horizontal', component: GripHorizontalIcon },
		// // { wip: true, name: 'grip-vertical', component: GripVerticalIcon },
		// // { wip: true, name: 'grip', component: GripIcon },
		// { wip: true, name: 'hammer', component: HammerIcon },
		// { wip: true, name: 'hand-coins', component: HandCoinsIcon },
		// { wip: true, name: 'hand-heart', component: HandHeartIcon },
		// { wip: true, name: 'hard-drive-download', component: HardDriveDownloadIcon },
		// { wip: true, name: 'hard-drive-upload', component: HardDriveUploadIcon },
		// { wip: true, name: 'headphone-off', component: HeadphoneOffIcon },
		{ name: 'heart-off', component: HeartOffIcon },
		{ name: 'heart', component: HeartIcon },
		// { wip: true, name: 'history', component: HistoryIcon },
		// { wip: true, name: 'hop-off', component: HopOffIcon },
		// { wip: true, name: 'house-wifi', component: HouseWifiIcon },
		// { wip: true, name: 'house', component: HouseIcon },
		// { wip: true, name: 'image-down', component: ImageDownIcon },
		// { wip: true, name: 'image-off', component: ImageOffIcon },
		// { wip: true, name: 'image-up', component: ImageUpIcon },
		// { wip: true, name: 'images', component: ImagesIcon },
		// { wip: true, name: 'infinity', component: InfinityIcon },
		// { wip: true, name: 'kanban', component: KanbanIcon },
		// { wip: true, name: 'key-round', component: KeyRoundIcon },
		// { wip: true, name: 'key-square', component: KeySquareIcon },
		// { wip: true, name: 'key', component: KeyIcon },
		// { wip: true, name: 'keyboard-off', component: KeyboardOffIcon },
		// // { wip: true, name: 'keyboard', component: KeyboardIcon },
		// { wip: true, name: 'landmark', component: LandmarkIcon },
		// { wip: true, name: 'layers', component: LayersIcon },
		// { wip: true, name: 'layout-dashboard', component: LayoutDashboardIcon },
		// { wip: true, name: 'layout-grid', component: LayoutGridIcon },
		// { wip: true, name: 'layout-panel-left', component: LayoutPanelLeftIcon },
		// { wip: true, name: 'layout-panel-top', component: LayoutPanelTopIcon },
		// { wip: true, name: 'layout-template', component: LayoutTemplateIcon },
		// { wip: true, name: 'lightbulb-off', component: LightbulbOffIcon },
		// { wip: true, name: 'lightbulb', component: LightbulbIcon },
		// { wip: true, name: 'link-2-off', component: Link2OffIcon },
		// { wip: true, name: 'list-check', component: ListCheckIcon },
		// { wip: true, name: 'list-checks', component: ListChecksIcon },
		// { wip: true, name: 'list-restart', component: ListRestartIcon },
		// { wip: true, name: 'list-todo', component: ListTodoIcon },
		// { wip: true, name: 'loader-pinwheel', component: LoaderPinwheelIcon },
		// { wip: true, name: 'locate-off', component: LocateOffIcon },
		// { wip: true, name: 'log-out', component: LogOutIcon },
		// { wip: true, name: 'mail-check', component: MailCheckIcon },
		// { wip: true, name: 'map-pin-check-inside', component: MapPinCheckInsideIcon },
		// { wip: true, name: 'map-pin-check', component: MapPinCheckIcon },
		// { wip: true, name: 'map-pin-off', component: MapPinOffIcon },
		// { wip: true, name: 'maximize-2', component: Maximize2Icon },
		// { wip: true, name: 'maximize', component: MaximizeIcon },
		// { wip: true, name: 'megaphone-off', component: MegaphoneOffIcon },
		// { wip: true, name: 'message-circle-more', component: MessageCircleMoreIcon },
		// { wip: true, name: 'message-circle-off', component: MessageCircleOffIcon },
		// { wip: true, name: 'message-circle-question-mark', component: MessageCircleQuestionMarkIcon },
		// { wip: true, name: 'message-circle-warning', component: MessageCircleWarningIcon },
		// { wip: true, name: 'message-circle', component: MessageCircleIcon },
		// { wip: true, name: 'message-square-more', component: MessageSquareMoreIcon },
		// { wip: true, name: 'message-square-off', component: MessageSquareOffIcon },
		// { wip: true, name: 'message-square', component: MessageSquareIcon },
		// { wip: true, name: 'mic-off', component: MicOffIcon },
		// { wip: true, name: 'milk-off', component: MilkOffIcon },
		// { wip: true, name: 'minimize-2', component: Minimize2Icon },
		// { wip: true, name: 'minimize', component: MinimizeIcon },
		// { wip: true, name: 'minus', component: MinusIcon },
		// { wip: true, name: 'monitor-check', component: MonitorCheckIcon },
		// { wip: true, name: 'monitor-cog', component: MonitorCogIcon },
		// { wip: true, name: 'monitor-down', component: MonitorDownIcon },
		// { wip: true, name: 'monitor-off', component: MonitorOffIcon },
		// { wip: true, name: 'monitor-up', component: MonitorUpIcon },
		// { wip: true, name: 'mouse-off', component: MouseOffIcon },
		// { wip: true, name: 'mouse-pointer-2', component: MousePointer2Icon },
		// { wip: true, name: 'mouse-pointer', component: MousePointerIcon },
		// { wip: true, name: 'move-diagonal-2', component: MoveDiagonal2Icon },
		// { wip: true, name: 'move-diagonal', component: MoveDiagonalIcon },
		// { wip: true, name: 'move-down-left', component: MoveDownLeftIcon },
		// { wip: true, name: 'move-down-right', component: MoveDownRightIcon },
		// { wip: true, name: 'move-down', component: MoveDownIcon },
		// { wip: true, name: 'move-horizontal', component: MoveHorizontalIcon },
		// { wip: true, name: 'move-left', component: MoveLeftIcon },
		// { wip: true, name: 'move-right', component: MoveRightIcon },
		// { wip: true, name: 'move-up-left', component: MoveUpLeftIcon },
		// { wip: true, name: 'move-up-right', component: MoveUpRightIcon },
		// { wip: true, name: 'move-up', component: MoveUpIcon },
		// { wip: true, name: 'move-vertical', component: MoveVerticalIcon },
		// { wip: true, name: 'navigation-2-off', component: Navigation2OffIcon },
		// { wip: true, name: 'navigation-off', component: NavigationOffIcon },
		// { wip: true, name: 'nfc', component: NfcIcon },
		// { wip: true, name: 'notebook-pen', component: NotebookPenIcon },
		// { wip: true, name: 'nut-off', component: NutOffIcon },
		// { wip: true, name: 'octagon-alert', component: OctagonAlertIcon },
		// { wip: true, name: 'orbit', component: OrbitIcon },
		// { wip: true, name: 'package-check', component: PackageCheckIcon },
		// { wip: true, name: 'paintbrush', component: PaintbrushIcon },
		// { wip: true, name: 'panel-bottom-close', component: PanelBottomCloseIcon },
		// { wip: true, name: 'panel-bottom-open', component: PanelBottomOpenIcon },
		// { wip: true, name: 'panel-left-close', component: PanelLeftCloseIcon },
		// { wip: true, name: 'panel-left-open', component: PanelLeftOpenIcon },
		// { wip: true, name: 'panel-right-close', component: PanelRightCloseIcon },
		// { wip: true, name: 'panel-right-open', component: PanelRightOpenIcon },
		// { wip: true, name: 'panel-top-close', component: PanelTopCloseIcon },
		// { wip: true, name: 'panel-top-open', component: PanelTopOpenIcon },
		// { wip: true, name: 'paperclip', component: PaperclipIcon },
		// { wip: true, name: 'pen-line', component: PenLineIcon },
		// { wip: true, name: 'pen-off', component: PenOffIcon },
		// { wip: true, name: 'pen', component: PenIcon },
		// { wip: true, name: 'pencil-line', component: PencilLineIcon },
		// { wip: true, name: 'pencil-off', component: PencilOffIcon },
		// { wip: true, name: 'pencil', component: PencilIcon },
		// { wip: true, name: 'phone-off', component: PhoneOffIcon },
		// { wip: true, name: 'pickaxe', component: PickaxeIcon },
		// { wip: true, name: 'pin-off', component: PinOffIcon },
		// // { wip: true, name: 'plane', component: PlaneIcon },
		// { wip: true, name: 'play', component: PlayIcon },
		// { wip: true, name: 'plus', component: PlusIcon },
		// { wip: true, name: 'pointer-off', component: PointerOffIcon },
		// { wip: true, name: 'power-off', component: PowerOffIcon },
		// { wip: true, name: 'printer-check', component: PrinterCheckIcon },
		// { wip: true, name: 'rabbit', component: RabbitIcon },
		// { wip: true, name: 'radar', component: RadarIcon },
		// { wip: true, name: 'radio-tower', component: RadioTowerIcon },
		// { wip: true, name: 'radio', component: RadioIcon },
		// { wip: true, name: 'rainbow', component: RainbowIcon },
		// { wip: true, name: 'redo-dot', component: RedoDotIcon },
		// { wip: true, name: 'redo', component: RedoIcon },
		// { wip: true, name: 'refresh-ccw-dot', component: RefreshCcwDotIcon },
		// { wip: true, name: 'refresh-ccw', component: RefreshCcwIcon },
		// { wip: true, name: 'refresh-cw-off', component: RefreshCwOffIcon },
		// { wip: true, name: 'refresh-cw', component: RefreshCwIcon },
		// { wip: true, name: 'rocket', component: RocketIcon },
		// { wip: true, name: 'rocking-chair', component: RockingChairIcon },
		// { wip: true, name: 'rotate-ccw-key', component: RotateCcwKeyIcon },
		// { wip: true, name: 'rotate-ccw', component: RotateCcwIcon },
		// { wip: true, name: 'rotate-cw', component: RotateCwIcon },
		// { wip: true, name: 'route-off', component: RouteOffIcon },
		// { wip: true, name: 'route', component: RouteIcon },
		{ name: 'rss', component: RssIcon },
		// { wip: true, name: 'save-off', component: SaveOffIcon },
		// { wip: true, name: 'scan-text', component: ScanTextIcon },
		// { wip: true, name: 'scissors', component: ScissorsIcon },
		{ name: 'search-check', component: SearchCheckIcon },
		{ name: 'search', component: SearchIcon },
		{ name: 'send-horizontal', component: SendHorizontalIcon },
		{ name: 'send', component: SendIcon },
		// { wip: true, name: 'server-cog', component: ServerCogIcon },
		// { wip: true, name: 'server-off', component: ServerOffIcon },
		// { wip: true, name: 'settings', component: SettingsIcon },
		// { wip: true, name: 'shield-alert', component: ShieldAlertIcon },
		// { wip: true, name: 'shield-check', component: ShieldCheckIcon },
		// { wip: true, name: 'shield-off', component: ShieldOffIcon },
		// { wip: true, name: 'shield-plus', component: ShieldPlusIcon },
		// { wip: true, name: 'shield-question-mark', component: ShieldQuestionMarkIcon },
		// { wip: true, name: 'ship-wheel', component: ShipWheelIcon },
		// { wip: true, name: 'ship', component: ShipIcon },
		// { wip: true, name: 'shopping-cart', component: ShoppingCartIcon },
		// { wip: true, name: 'shovel', component: ShovelIcon },
		// // { wip: true, name: 'shower-head', component: ShowerHeadIcon },
		// { wip: true, name: 'shrink', component: ShrinkIcon },
		// { wip: true, name: 'signal-high', component: SignalHighIcon },
		// { wip: true, name: 'signal-low', component: SignalLowIcon },
		// { wip: true, name: 'signal-medium', component: SignalMediumIcon },
		// { wip: true, name: 'signal-zero', component: SignalZeroIcon },
		// { wip: true, name: 'signal', component: SignalIcon },
		// { wip: true, name: 'signature', component: SignatureIcon },
		// { wip: true, name: 'sliders-horizontal', component: SlidersHorizontalIcon },
		// { wip: true, name: 'sliders-vertical', component: SlidersVerticalIcon },
		// { wip: true, name: 'smartphone-nfc', component: SmartphoneNfcIcon },
		// { wip: true, name: 'snowflake', component: SnowflakeIcon },
		// { wip: true, name: 'sparkle', component: SparkleIcon },
		// { wip: true, name: 'sparkles', component: SparklesIcon },
		// { wip: true, name: 'speech', component: SpeechIcon },
		// { wip: true, name: 'spell-check', component: SpellCheckIcon },
		// { wip: true, name: 'square-arrow-down-left', component: SquareArrowDownLeftIcon },
		// { wip: true, name: 'square-arrow-down-right', component: SquareArrowDownRightIcon },
		// { wip: true, name: 'square-arrow-down', component: SquareArrowDownIcon },
		// { wip: true, name: 'square-arrow-left', component: SquareArrowLeftIcon },
		// { wip: true, name: 'square-arrow-out-down-left', component: SquareArrowOutDownLeftIcon },
		// { wip: true, name: 'square-arrow-out-down-right', component: SquareArrowOutDownRightIcon },
		// { wip: true, name: 'square-arrow-out-up-left', component: SquareArrowOutUpLeftIcon },
		// { wip: true, name: 'square-arrow-out-up-right', component: SquareArrowOutUpRightIcon },
		// { wip: true, name: 'square-arrow-right', component: SquareArrowRightIcon },
		// { wip: true, name: 'square-arrow-up-left', component: SquareArrowUpLeftIcon },
		// { wip: true, name: 'square-arrow-up-right', component: SquareArrowUpRightIcon },
		// { wip: true, name: 'square-arrow-up', component: SquareArrowUpIcon },
		// { wip: true, name: 'square-chart-gantt', component: SquareChartGanttIcon },
		// { wip: true, name: 'square-check-big', component: SquareCheckBigIcon },
		// { wip: true, name: 'square-check', component: SquareCheckIcon },
		// { wip: true, name: 'square-chevron-down', component: SquareChevronDownIcon },
		// { wip: true, name: 'square-chevron-left', component: SquareChevronLeftIcon },
		// { wip: true, name: 'square-chevron-right', component: SquareChevronRightIcon },
		// { wip: true, name: 'square-chevron-up', component: SquareChevronUpIcon },
		// { wip: true, name: 'square-dashed-kanban', component: SquareDashedKanbanIcon },
		// { wip: true, name: 'square-kanban', component: SquareKanbanIcon },
		// { wip: true, name: 'square-parking-off', component: SquareParkingOffIcon },
		// { wip: true, name: 'square-pen', component: SquarePenIcon },
		// { wip: true, name: 'square-plus', component: SquarePlusIcon },
		// { wip: true, name: 'square-scissors', component: SquareScissorsIcon },
		// { wip: true, name: 'square-stack', component: SquareStackIcon },
		// { wip: true, name: 'square-terminal', component: SquareTerminalIcon },
		{ name: 'star-off', component: StarOffIcon },
		{ name: 'star', component: StarIcon },
		// // { wip: true, name: 'sun', component: SunIcon },
		// { wip: true, name: 'sword', component: SwordIcon },
		// { wip: true, name: 'tag', component: TagIcon },
		// { wip: true, name: 'telescope', component: TelescopeIcon },
		// { wip: true, name: 'terminal', component: TerminalIcon },
		// { wip: true, name: 'text-align-center', component: TextAlignCenterIcon },
		// { wip: true, name: 'text-cursor-input', component: TextCursorInputIcon },
		// { wip: true, name: 'text-cursor', component: TextCursorIcon },
		// { wip: true, name: 'text-search', component: TextSearchIcon },
		// { wip: true, name: 'thermometer', component: ThermometerIcon },
		// { wip: true, name: 'thumbs-down', component: ThumbsDownIcon },
		// { wip: true, name: 'thumbs-up', component: ThumbsUpIcon },
		// { wip: true, name: 'ticket-check', component: TicketCheckIcon },
		// { wip: true, name: 'timer-off', component: TimerOffIcon },
		// { wip: true, name: 'timer', component: TimerIcon },
		// { wip: true, name: 'toggle-left', component: ToggleLeftIcon },
		// { wip: true, name: 'toggle-right', component: ToggleRightIcon },
		// { wip: true, name: 'tornado', component: TornadoIcon },
		// { wip: true, name: 'touchpad-off', component: TouchpadOffIcon },
		// { wip: true, name: 'trash-2', component: Trash2Icon },
		// { wip: true, name: 'trash', component: TrashIcon },
		// { wip: true, name: 'triangle-alert', component: TriangleAlertIcon },
		// { wip: true, name: 'umbrella-off', component: UmbrellaOffIcon },
		// { wip: true, name: 'undo-dot', component: UndoDotIcon },
		// { wip: true, name: 'undo', component: UndoIcon },
		// { wip: true, name: 'unfold-horizontal', component: UnfoldHorizontalIcon },
		// { wip: true, name: 'unfold-vertical', component: UnfoldVerticalIcon },
		// { wip: true, name: 'unplug', component: UnplugIcon },
		// { wip: true, name: 'upload', component: UploadIcon },
		// { wip: true, name: 'user-check', component: UserCheckIcon },
		// { wip: true, name: 'user-cog', component: UserCogIcon },
		// { wip: true, name: 'user-pen', component: UserPenIcon },
		// { wip: true, name: 'user-round-check', component: UserRoundCheckIcon },
		// { wip: true, name: 'user-round-cog', component: UserRoundCogIcon },
		// { wip: true, name: 'user-round-pen', component: UserRoundPenIcon },
		// { wip: true, name: 'user-round', component: UserRoundIcon },
		// { wip: true, name: 'user', component: UserIcon },
		// { wip: true, name: 'vibrate-off', component: VibrateOffIcon },
		// { wip: true, name: 'vibrate', component: VibrateIcon },
		// { wip: true, name: 'video-off', component: VideoOffIcon },
		// { wip: true, name: 'volume-off', component: VolumeOffIcon },
		// { wip: true, name: 'vote', component: VoteIcon },
		// { wip: true, name: 'waves', component: WavesIcon },
		// { wip: true, name: 'webhook-off', component: WebhookOffIcon },
		// { wip: true, name: 'wheat-off', component: WheatOffIcon },
		// { wip: true, name: 'wifi-high', component: WifiHighIcon },
		// { wip: true, name: 'wifi-low', component: WifiLowIcon },
		// { wip: true, name: 'wifi-off', component: WifiOffIcon },
		// { wip: true, name: 'wifi-pen', component: WifiPenIcon },
		// { wip: true, name: 'wifi-zero', component: WifiZeroIcon },
		// { wip: true, name: 'wifi', component: WifiIcon },
		// { wip: true, name: 'wine-off', component: WineOffIcon },
		// { wip: true, name: 'x', component: XIcon },
		{ wip: false, name: 'zap-off', component: ZapOffIcon },
	]);

	cleanSearchTerm = computed(() => this.searchTerm().trim().toLowerCase());

	availableIcons = computed(() => this.icons().filter((icon) => this.includeWip() || !icon.wip));

	filteredIcons = computed(() => {
		const searchTerm = this.cleanSearchTerm();
		const icons = this.availableIcons();

		if (!searchTerm) {
			return icons;
		}

		return icons.filter((icon) => icon.name.includes(searchTerm));
	});

	iconCountMessage = computed(() => {
		const icons = this.availableIcons();
		const filteredIcons = this.filteredIcons();
		if (icons.length === filteredIcons.length) {
			return `${icons.length} icons`;
		}

		return `${filteredIcons.length}/${icons.length} icons`;
	});
}
