import {
	AccessibilityIcon,
	ActivityIcon,
	AirplayIcon,
	AlarmClockCheckIcon,
	AlarmClockIcon,
	AlarmClockOffIcon,
	AlignHorizontalSpaceAroundIcon,
	AlignVerticalSpaceAroundIcon,
	AnvilIcon,
	ArchiveIcon,
	ArrowBigDownDashIcon,
	ArrowBigDownIcon,
	ArrowBigLeftDashIcon,
	ArrowBigLeftIcon,
	ArrowBigRightDashIcon,
	ArrowBigRightIcon,
	ArrowBigUpDashIcon,
	ArrowBigUpIcon,
	ArrowDown01Icon,
	ArrowDown10Icon,
	ArrowDownAZIcon,
	ArrowDownLeftIcon,
	ArrowDownRightIcon,
	ArrowDownZAIcon,
	ArrowDownIcon,
	ArrowLeftRightIcon,
	ArrowLeftIcon,
	ArrowRightLeftIcon,
	ArrowRightIcon,
	ArrowUp01Icon,
	ArrowUp10Icon,
	ArrowUpAZIcon,
	ArrowUpLeftIcon,
	ArrowUpRightIcon,
	ArrowUpZAIcon,
	ArrowUpIcon,
	AudioLinesIcon,
	AwardIcon,
	AxeIcon,
	Axis3dIcon,
	BadgeAlertIcon,
	BadgeCheckIcon,
	BadgeQuestionMarkIcon,
	BatteryChargingIcon,
	BatteryFullIcon,
	BatteryLowIcon,
	BatteryMediumIcon,
	BatteryWarningIcon,
	BatteryIcon,
	BeanOffIcon,
	BeerOffIcon,
	BellOffIcon,
	BellRingIcon,
	BellIcon,
	BetweenHorizontalEndIcon,
	BetweenHorizontalStartIcon,
	BetweenVerticalEndIcon,
	BetweenVerticalStartIcon,
	BinaryIcon,
	BlendIcon,
	BlocksIcon,
	BluetoothOffIcon,
	BoldIcon,
	BoltIcon,
	BoneIcon,
	BookAIcon,
	BookAudioIcon,
	BookCheckIcon,
	BookDashedIcon,
	BookDownIcon,
	BookHeadphonesIcon,
	BookHeartIcon,
	BookImageIcon,
	BookKeyIcon,
	BookLockIcon,
	BookMarkedIcon,
	BookMinusIcon,
	BookOpenCheckIcon,
	BookOpenTextIcon,
	BookPlusIcon,
	BookTextIcon,
	BookTypeIcon,
	BookUp2Icon,
	BookUpIcon,
	BookUserIcon,
	BookXIcon,
	BookIcon,
	BookmarkCheckIcon,
	BookmarkMinusIcon,
	BookmarkPlusIcon,
	BookmarkXIcon,
	BookmarkIcon,
	BotOffIcon,
	BotIcon,
	BoxesIcon,
	BrainCogIcon,
	BriefcaseBusinessIcon,
	BriefcaseConveyorBeltIcon,
	BriefcaseMedicalIcon,
	BriefcaseIcon,
	BrushCleaningIcon,
	BrushIcon,
	BugOffIcon,
	CalendarCheck2Icon,
	CalendarCheckIcon,
	CalendarCogIcon,
	CalendarDaysIcon,
	CalendarOffIcon,
	CalendarSyncIcon,
	CameraOffIcon,
	CandyOffIcon,
	CaptionsOffIcon,
	CastIcon,
	CctvIcon,
	ChartBarDecreasingIcon,
	ChartBarIncreasingIcon,
	ChartBarIcon,
	ChartColumnDecreasingIcon,
	ChartColumnIncreasingIcon,
	ChartColumnIcon,
	ChartGanttIcon,
	ChartLineIcon,
	ChartNoAxesColumnDecreasingIcon,
	ChartNoAxesColumnIncreasingIcon,
	ChartNoAxesColumnIcon,
	ChartNoAxesCombinedIcon,
	ChartNoAxesGanttIcon,
	ChartPieIcon,
	ChartScatterIcon,
	ChartSplineIcon,
	CheckCheckIcon,
	CheckIcon,
	CherryIcon,
	ChevronDownIcon,
	ChevronLeftIcon,
	ChevronRightIcon,
	ChevronUpIcon,
	ChevronsDownUpIcon,
	ChevronsDownIcon,
	ChevronsLeftRightIcon,
	ChevronsLeftIcon,
	ChevronsRightLeftIcon,
	ChevronsRightIcon,
	ChevronsUpDownIcon,
	ChevronsUpIcon,
	CigaretteOffIcon,
	CircleAlertIcon,
	CircleArrowDownIcon,
	CircleArrowLeftIcon,
	CircleArrowOutDownLeftIcon,
	CircleArrowOutDownRightIcon,
	CircleArrowOutUpLeftIcon,
	CircleArrowOutUpRightIcon,
	CircleArrowRightIcon,
	CircleArrowUpIcon,
	CircleCheckBigIcon,
	CircleCheckIcon,
	CircleChevronDownIcon,
	CircleChevronLeftIcon,
	CircleChevronRightIcon,
	CircleChevronUpIcon,
	CircleOffIcon,
	CircleParkingOffIcon,
	CirclePlusIcon,
	CircleQuestionMarkIcon,
	ClapperboardIcon,
	ClipboardCheckIcon,
	ClipboardListIcon,
	ClipboardPenLineIcon,
	ClipboardPenIcon,
	ClipboardXIcon,
	ClipboardIcon,
	Clock1Icon,
	Clock10Icon,
	Clock11Icon,
	Clock12Icon,
	Clock2Icon,
	Clock3Icon,
	Clock4Icon,
	Clock5Icon,
	Clock6Icon,
	Clock7Icon,
	Clock8Icon,
	Clock9Icon,
	ClockIcon,
	CloudCogIcon,
	CloudDownloadIcon,
	CloudMoonIcon,
	CloudOffIcon,
	CloudUploadIcon,
	CogIcon,
	CompassIcon,
	ContrastIcon,
	CopyCheckIcon,
	CopyIcon,
	CpuIcon,
	CropIcon,
	DiamondPlusIcon,
	Dice1Icon,
	Dice2Icon,
	Dice3Icon,
	Dice4Icon,
	Dice5Icon,
	Dice6Icon,
	DiffIcon,
	DnaOffIcon,
	DownloadIcon,
	DropletOffIcon,
	DrumIcon,
	EarOffIcon,
	EclipseIcon,
	EggOffIcon,
	ExpandIcon,
	EyeOffIcon,
	FileChartColumnIncreasingIcon,
	FileChartColumnIcon,
	FileChartLineIcon,
	FileCheckCornerIcon,
	FileCheckIcon,
	FileCogIcon,
	FileDownIcon,
	FileMinusIcon,
	FilePenLineIcon,
	FilePenIcon,
	FilePlusIcon,
	FileQuestionMarkIcon,
	FileSlidersIcon,
	FileStackIcon,
	FileTerminalIcon,
	FileUpIcon,
	FishOffIcon,
	FlagOffIcon,
	FlashlightOffIcon,
	FlaskConicalOffIcon,
	FolderCheckIcon,
	FolderCogIcon,
	FolderDownIcon,
	FolderKanbanIcon,
	FolderPenIcon,
	FolderPlusIcon,
	FolderSyncIcon,
	FolderUpIcon,
	FolderXIcon,
	FrameIcon,
	GalleryHorizontalEndIcon,
	GalleryHorizontalIcon,
	GalleryThumbnailsIcon,
	GalleryVerticalEndIcon,
	GalleryVerticalIcon,
	GaugeIcon,
	GavelIcon,
	Grid2x2CheckIcon,
	GripHorizontalIcon,
	GripVerticalIcon,
	GripIcon,
	HammerIcon,
	HandCoinsIcon,
	HandHeartIcon,
	HardDriveDownloadIcon,
	HardDriveUploadIcon,
	HeadphoneOffIcon,
	HeartOffIcon,
	HeartIcon,
	HistoryIcon,
	HopOffIcon,
	HouseWifiIcon,
	HouseIcon,
	ImageDownIcon,
	ImageOffIcon,
	ImageUpIcon,
	ImagesIcon,
	InfinityIcon,
	KanbanIcon,
	KeyRoundIcon,
	KeySquareIcon,
	KeyIcon,
	KeyboardOffIcon,
	KeyboardIcon,
	LandmarkIcon,
	LayersIcon,
	LayoutDashboardIcon,
	LayoutGridIcon,
	LayoutPanelLeftIcon,
	LayoutPanelTopIcon,
	LayoutTemplateIcon,
	LightbulbOffIcon,
	LightbulbIcon,
	Link2OffIcon,
	ListCheckIcon,
	ListChecksIcon,
	ListRestartIcon,
	ListTodoIcon,
	LoaderPinwheelIcon,
	LocateOffIcon,
	LogOutIcon,
	MailCheckIcon,
	MapPinCheckInsideIcon,
	MapPinCheckIcon,
	MapPinOffIcon,
	Maximize2Icon,
	MaximizeIcon,
	MegaphoneOffIcon,
	MessageCircleMoreIcon,
	MessageCircleOffIcon,
	MessageCircleQuestionMarkIcon,
	MessageCircleWarningIcon,
	MessageCircleIcon,
	MessageSquareMoreIcon,
	MessageSquareOffIcon,
	MessageSquareIcon,
	MicOffIcon,
	MilkOffIcon,
	Minimize2Icon,
	MinimizeIcon,
	MinusIcon,
	MonitorCheckIcon,
	MonitorCogIcon,
	MonitorDownIcon,
	MonitorOffIcon,
	MonitorUpIcon,
	MouseOffIcon,
	MousePointer2Icon,
	MousePointerIcon,
	MoveDiagonal2Icon,
	MoveDiagonalIcon,
	MoveDownLeftIcon,
	MoveDownRightIcon,
	MoveDownIcon,
	MoveHorizontalIcon,
	MoveLeftIcon,
	MoveRightIcon,
	MoveUpLeftIcon,
	MoveUpRightIcon,
	MoveUpIcon,
	MoveVerticalIcon,
	Navigation2OffIcon,
	NavigationOffIcon,
	NfcIcon,
	NotebookPenIcon,
	NutOffIcon,
	OctagonAlertIcon,
	OrbitIcon,
	PackageCheckIcon,
	PaintbrushIcon,
	PanelBottomCloseIcon,
	PanelBottomOpenIcon,
	PanelLeftCloseIcon,
	PanelLeftOpenIcon,
	PanelRightCloseIcon,
	PanelRightOpenIcon,
	PanelTopCloseIcon,
	PanelTopOpenIcon,
	PaperclipIcon,
	PenLineIcon,
	PenOffIcon,
	PenIcon,
	PencilLineIcon,
	PencilOffIcon,
	PencilIcon,
	PhoneOffIcon,
	PickaxeIcon,
	PinOffIcon,
	PlaneIcon,
	PlayIcon,
	PlusIcon,
	PointerOffIcon,
	PowerOffIcon,
	PrinterCheckIcon,
	RabbitIcon,
	RadarIcon,
	RadioTowerIcon,
	RadioIcon,
	RainbowIcon,
	RedoDotIcon,
	RedoIcon,
	RefreshCcwDotIcon,
	RefreshCcwIcon,
	RefreshCwOffIcon,
	RefreshCwIcon,
	RocketIcon,
	RockingChairIcon,
	RotateCcwKeyIcon,
	RotateCcwIcon,
	RotateCwIcon,
	RouteOffIcon,
	RouteIcon,
	RssIcon,
	SaveOffIcon,
	ScanTextIcon,
	ScissorsIcon,
	SearchCheckIcon,
	SearchIcon,
	SendHorizontalIcon,
	SendIcon,
	ServerCogIcon,
	ServerOffIcon,
	SettingsIcon,
	ShieldAlertIcon,
	ShieldCheckIcon,
	ShieldOffIcon,
	ShieldPlusIcon,
	ShieldQuestionMarkIcon,
	ShipWheelIcon,
	ShipIcon,
	ShoppingCartIcon,
	ShovelIcon,
	ShowerHeadIcon,
	ShrinkIcon,
	SignalHighIcon,
	SignalLowIcon,
	SignalMediumIcon,
	SignalZeroIcon,
	SignalIcon,
	SignatureIcon,
	SlidersHorizontalIcon,
	SlidersVerticalIcon,
	SmartphoneNfcIcon,
	SnowflakeIcon,
	SparkleIcon,
	SparklesIcon,
	SpeechIcon,
	SpellCheckIcon,
	SquareArrowDownLeftIcon,
	SquareArrowDownRightIcon,
	SquareArrowDownIcon,
	SquareArrowLeftIcon,
	SquareArrowOutDownLeftIcon,
	SquareArrowOutDownRightIcon,
	SquareArrowOutUpLeftIcon,
	SquareArrowOutUpRightIcon,
	SquareArrowRightIcon,
	SquareArrowUpLeftIcon,
	SquareArrowUpRightIcon,
	SquareArrowUpIcon,
	SquareChartGanttIcon,
	SquareCheckBigIcon,
	SquareCheckIcon,
	SquareChevronDownIcon,
	SquareChevronLeftIcon,
	SquareChevronRightIcon,
	SquareChevronUpIcon,
	SquareDashedKanbanIcon,
	SquareKanbanIcon,
	SquareParkingOffIcon,
	SquarePenIcon,
	SquarePlusIcon,
	SquareScissorsIcon,
	SquareStackIcon,
	SquareTerminalIcon,
	StarOffIcon,
	StarIcon,
	SunIcon,
	SwordIcon,
	TagIcon,
	TelescopeIcon,
	TerminalIcon,
	TextAlignCenterIcon,
	TextCursorInputIcon,
	TextCursorIcon,
	TextSearchIcon,
	ThermometerIcon,
	ThumbsDownIcon,
	ThumbsUpIcon,
	TicketCheckIcon,
	TimerOffIcon,
	TimerIcon,
	ToggleLeftIcon,
	ToggleRightIcon,
	TornadoIcon,
	TouchpadOffIcon,
	Trash2Icon,
	TrashIcon,
	TriangleAlertIcon,
	UmbrellaOffIcon,
	UndoDotIcon,
	UndoIcon,
	UnfoldHorizontalIcon,
	UnfoldVerticalIcon,
	UnplugIcon,
	UploadIcon,
	UserCheckIcon,
	UserCogIcon,
	UserPenIcon,
	UserRoundCheckIcon,
	UserRoundCogIcon,
	UserRoundPenIcon,
	UserRoundIcon,
	UserIcon,
	VibrateOffIcon,
	VibrateIcon,
	VideoOffIcon,
	VolumeOffIcon,
	VoteIcon,
	WavesIcon,
	WebhookOffIcon,
	WheatOffIcon,
	WifiHighIcon,
	WifiLowIcon,
	WifiOffIcon,
	WifiPenIcon,
	WifiZeroIcon,
	WifiIcon,
	WineOffIcon,
	XIcon,
	ZapOffIcon,
} from 'ng-animated-icons';
import { IconItem } from './icon-item.type';

export const ICONS_LIST: IconItem[] = [
	{ name: 'accessibility', component: AccessibilityIcon },
	{ name: 'activity', component: ActivityIcon },
	{ name: 'airplay', component: AirplayIcon },
	{ name: 'alarm-clock-check', component: AlarmClockCheckIcon },
	{ name: 'alarm-clock-off', component: AlarmClockOffIcon },
	{ name: 'alarm-clock', component: AlarmClockIcon },
	{ name: 'align-horizontal-space-around', component: AlignHorizontalSpaceAroundIcon },
	{ name: 'align-vertical-space-around', component: AlignVerticalSpaceAroundIcon },
	{ name: 'anvil', component: AnvilIcon },
	{ name: 'archive', component: ArchiveIcon },
	{ name: 'arrow-big-down-dash', component: ArrowBigDownDashIcon },
	{ name: 'arrow-big-down', component: ArrowBigDownIcon },
	{ name: 'arrow-big-left-dash', component: ArrowBigLeftDashIcon },
	{ name: 'arrow-big-left', component: ArrowBigLeftIcon },
	{ name: 'arrow-big-right-dash', component: ArrowBigRightDashIcon },
	{ name: 'arrow-big-right', component: ArrowBigRightIcon },
	{ name: 'arrow-big-up-dash', component: ArrowBigUpDashIcon },
	{ name: 'arrow-big-up', component: ArrowBigUpIcon },
	{ name: 'arrow-down-0-1', component: ArrowDown01Icon },
	{ name: 'arrow-down-1-0', component: ArrowDown10Icon },
	{ name: 'arrow-down-a-z', component: ArrowDownAZIcon },
	{ name: 'arrow-down-left', component: ArrowDownLeftIcon },
	{ name: 'arrow-down-right', component: ArrowDownRightIcon },
	{ name: 'arrow-down-z-a', component: ArrowDownZAIcon },
	{ name: 'arrow-down', component: ArrowDownIcon },
	{ name: 'arrow-left-right', component: ArrowLeftRightIcon },
	{ name: 'arrow-left', component: ArrowLeftIcon },
	{ name: 'arrow-right-left', component: ArrowRightLeftIcon },
	{ name: 'arrow-right', component: ArrowRightIcon },
	{ name: 'arrow-up-0-1', component: ArrowUp01Icon },
	{ name: 'arrow-up-1-0', component: ArrowUp10Icon },
	{ name: 'arrow-up-a-z', component: ArrowUpAZIcon },
	{ name: 'arrow-up-left', component: ArrowUpLeftIcon },
	{ name: 'arrow-up-right', component: ArrowUpRightIcon },
	{ name: 'arrow-up-z-a', component: ArrowUpZAIcon },
	{ name: 'arrow-up', component: ArrowUpIcon },
	// { wip: true, name: 'audio-lines', component: AudioLinesIcon },
	{ name: 'award', component: AwardIcon },
	{ name: 'axe', component: AxeIcon },
	{ name: 'axis-3d', component: Axis3dIcon },
	{ name: 'badge-alert', component: BadgeAlertIcon },
	{ name: 'badge-check', component: BadgeCheckIcon },
	{ name: 'badge-question-mark', component: BadgeQuestionMarkIcon },
	{ name: 'battery-charging', component: BatteryChargingIcon },
	{ name: 'battery-full', component: BatteryFullIcon },
	{ name: 'battery-low', component: BatteryLowIcon },
	{ name: 'battery-medium', component: BatteryMediumIcon },
	{ name: 'battery-warning', component: BatteryWarningIcon },
	{ name: 'battery', component: BatteryIcon },
	{ name: 'bean-off', component: BeanOffIcon },
	{ name: 'beer-off', component: BeerOffIcon },
	{ name: 'bell-off', component: BellOffIcon },
	{ name: 'bell-ring', component: BellRingIcon },
	{ name: 'bell', component: BellIcon },
	{ name: 'between-horizontal-end', component: BetweenHorizontalEndIcon },
	{ name: 'between-horizontal-start', component: BetweenHorizontalStartIcon },
	{ name: 'between-vertical-end', component: BetweenVerticalEndIcon },
	{ name: 'between-vertical-start', component: BetweenVerticalStartIcon },
	{ name: 'binary', component: BinaryIcon },
	{ name: 'blend', component: BlendIcon },
	{ name: 'blocks', component: BlocksIcon },
	{ name: 'bluetooth-off', component: BluetoothOffIcon },
	{ name: 'bold', component: BoldIcon },
	{ name: 'bolt', component: BoltIcon },
	{ name: 'bone', component: BoneIcon },
	{ name: 'book-a', component: BookAIcon },
	{ name: 'book-audio', component: BookAudioIcon },
	{ name: 'book-check', component: BookCheckIcon },
	{ name: 'book-dashed', component: BookDashedIcon },
	{ name: 'book-down', component: BookDownIcon },
	{ name: 'book-headphones', component: BookHeadphonesIcon },
	{ name: 'book-heart', component: BookHeartIcon },
	{ name: 'book-image', component: BookImageIcon },
	{ name: 'book-key', component: BookKeyIcon },
	{ name: 'book-lock', component: BookLockIcon },
	{ name: 'book-marked', component: BookMarkedIcon },
	{ name: 'book-minus', component: BookMinusIcon },
	{ name: 'book-open-check', component: BookOpenCheckIcon },
	{ name: 'book-open-text', component: BookOpenTextIcon },
	{ name: 'book-plus', component: BookPlusIcon },
	{ name: 'book-text', component: BookTextIcon },
	{ name: 'book-type', component: BookTypeIcon },
	{ name: 'book-up-2', component: BookUp2Icon },
	{ name: 'book-up', component: BookUpIcon },
	{ name: 'book-user', component: BookUserIcon },
	{ name: 'book-x', component: BookXIcon },
	{ name: 'book', component: BookIcon },
	{ name: 'bookmark-check', component: BookmarkCheckIcon },
	{ name: 'bookmark-minus', component: BookmarkMinusIcon },
	{ name: 'bookmark-plus', component: BookmarkPlusIcon },
	{ name: 'bookmark-x', component: BookmarkXIcon },
	{ name: 'bookmark', component: BookmarkIcon },
	{ name: 'bot-off', component: BotOffIcon },
	{ name: 'bot', component: BotIcon },
	{ name: 'boxes', component: BoxesIcon },
	{ name: 'brain-cog', component: BrainCogIcon },
	{ name: 'briefcase-business', component: BriefcaseBusinessIcon },
	{ name: 'briefcase-conveyor-belt', component: BriefcaseConveyorBeltIcon },
	{ name: 'briefcase-medical', component: BriefcaseMedicalIcon },
	{ name: 'briefcase', component: BriefcaseIcon },
	{ name: 'brush-cleaning', component: BrushCleaningIcon },
	{ name: 'brush', component: BrushIcon },
	{ name: 'bug-off', component: BugOffIcon },
	{ name: 'calendar-check-2', component: CalendarCheck2Icon },
	{ name: 'calendar-check', component: CalendarCheckIcon },
	{ name: 'calendar-cog', component: CalendarCogIcon },
	{ name: 'calendar-days', component: CalendarDaysIcon },
	{ name: 'calendar-off', component: CalendarOffIcon },
	{ name: 'calendar-sync', component: CalendarSyncIcon },
	{ name: 'camera-off', component: CameraOffIcon },
	{ name: 'candy-off', component: CandyOffIcon },
	{ name: 'captions-off', component: CaptionsOffIcon },
	{ name: 'cast', component: CastIcon },
	{ name: 'cctv', component: CctvIcon },
	{ name: 'chart-bar-decreasing', component: ChartBarDecreasingIcon },
	{ name: 'chart-bar-increasing', component: ChartBarIncreasingIcon },
	{ name: 'chart-bar', component: ChartBarIcon },
	{ name: 'chart-column-decreasing', component: ChartColumnDecreasingIcon },
	{ name: 'chart-column-increasing', component: ChartColumnIncreasingIcon },
	{ name: 'chart-column', component: ChartColumnIcon },
	{ name: 'chart-gantt', component: ChartGanttIcon },
	{ name: 'chart-line', component: ChartLineIcon },
	{ name: 'chart-no-axes-column-decreasing', component: ChartNoAxesColumnDecreasingIcon },
	{ name: 'chart-no-axes-column-increasing', component: ChartNoAxesColumnIncreasingIcon },
	{ name: 'chart-no-axes-column', component: ChartNoAxesColumnIcon },
	{ name: 'chart-no-axes-combined', component: ChartNoAxesCombinedIcon },
	{ name: 'chart-no-axes-gantt', component: ChartNoAxesGanttIcon },
	{ name: 'chart-pie', component: ChartPieIcon },
	{ name: 'chart-scatter', component: ChartScatterIcon },
	{ name: 'chart-spline', component: ChartSplineIcon },
	{ name: 'check-check', component: CheckCheckIcon },
	{ name: 'check', component: CheckIcon },
	{ name: 'cherry', component: CherryIcon },
	{ name: 'chevron-down', component: ChevronDownIcon },
	{ name: 'chevron-left', component: ChevronLeftIcon },
	{ name: 'chevron-right', component: ChevronRightIcon },
	{ name: 'chevron-up', component: ChevronUpIcon },
	{ name: 'chevrons-down-up', component: ChevronsDownUpIcon },
	{ name: 'chevrons-down', component: ChevronsDownIcon },
	{ name: 'chevrons-left-right', component: ChevronsLeftRightIcon },
	{ name: 'chevrons-left', component: ChevronsLeftIcon },
	{ name: 'chevrons-right-left', component: ChevronsRightLeftIcon },
	{ name: 'chevrons-right', component: ChevronsRightIcon },
	{ name: 'chevrons-up-down', component: ChevronsUpDownIcon },
	{ name: 'chevrons-up', component: ChevronsUpIcon },
	{ name: 'cigarette-off', component: CigaretteOffIcon },
	{ name: 'circle-alert', component: CircleAlertIcon },
	{ name: 'circle-arrow-down', component: CircleArrowDownIcon },
	{ name: 'circle-arrow-left', component: CircleArrowLeftIcon },
	{ name: 'circle-arrow-out-down-left', component: CircleArrowOutDownLeftIcon },
	{ name: 'circle-arrow-out-down-right', component: CircleArrowOutDownRightIcon },
	{ name: 'circle-arrow-out-up-left', component: CircleArrowOutUpLeftIcon },
	{ name: 'circle-arrow-out-up-right', component: CircleArrowOutUpRightIcon },
	{ name: 'circle-arrow-right', component: CircleArrowRightIcon },
	{ name: 'circle-arrow-up', component: CircleArrowUpIcon },
	{ name: 'circle-check-big', component: CircleCheckBigIcon },
	{ name: 'circle-check', component: CircleCheckIcon },
	{ name: 'circle-chevron-down', component: CircleChevronDownIcon },
	{ name: 'circle-chevron-left', component: CircleChevronLeftIcon },
	{ name: 'circle-chevron-right', component: CircleChevronRightIcon },
	{ name: 'circle-chevron-up', component: CircleChevronUpIcon },
	{ name: 'circle-off', component: CircleOffIcon },
	{ name: 'circle-parking-off', component: CircleParkingOffIcon },
	{ name: 'circle-plus', component: CirclePlusIcon },
	{ name: 'circle-question-mark', component: CircleQuestionMarkIcon },
	{ name: 'clapperboard', component: ClapperboardIcon },
	{ name: 'clipboard-check', component: ClipboardCheckIcon },
	{ name: 'clipboard-list', component: ClipboardListIcon },
	{ name: 'clipboard-pen-line', component: ClipboardPenLineIcon },
	{ name: 'clipboard-pen', component: ClipboardPenIcon },
	{ name: 'clipboard-x', component: ClipboardXIcon },
	{ name: 'clipboard', component: ClipboardIcon },
	{ name: 'clock', component: ClockIcon },
	{ name: 'clock-1', component: Clock1Icon },
	{ name: 'clock-2', component: Clock2Icon },
	{ name: 'clock-3', component: Clock3Icon },
	{ name: 'clock-4', component: Clock4Icon },
	{ name: 'clock-5', component: Clock5Icon },
	{ name: 'clock-6', component: Clock6Icon },
	{ name: 'clock-7', component: Clock7Icon },
	{ name: 'clock-8', component: Clock8Icon },
	{ name: 'clock-9', component: Clock9Icon },
	{ name: 'clock-10', component: Clock10Icon },
	{ name: 'clock-11', component: Clock11Icon },
	{ name: 'clock-12', component: Clock12Icon },
	{ name: 'cloud-cog', component: CloudCogIcon },
	{ name: 'cloud-download', component: CloudDownloadIcon },
	{ name: 'cloud-moon', component: CloudMoonIcon },
	{ name: 'cloud-off', component: CloudOffIcon },
	{ name: 'cloud-upload', component: CloudUploadIcon },
	{ name: 'cog', component: CogIcon },
	{ name: 'compass', component: CompassIcon },
	{ name: 'contrast', component: ContrastIcon },
	{ name: 'copy-check', component: CopyCheckIcon },
	{ name: 'copy', component: CopyIcon },
	{ name: 'cpu', component: CpuIcon },
	{ name: 'crop', component: CropIcon },
	{ name: 'diamond-plus', component: DiamondPlusIcon },
	{ name: 'dice-1', component: Dice1Icon },
	{ name: 'dice-2', component: Dice2Icon },
	{ name: 'dice-3', component: Dice3Icon },
	{ name: 'dice-4', component: Dice4Icon },
	{ name: 'dice-5', component: Dice5Icon },
	{ name: 'dice-6', component: Dice6Icon },
	{ name: 'diff', component: DiffIcon },
	{ name: 'dna-off', component: DnaOffIcon },
	{ name: 'download', component: DownloadIcon },
	{ name: 'droplet-off', component: DropletOffIcon },
	{ name: 'drum', component: DrumIcon },
	{ name: 'ear-off', component: EarOffIcon },
	{ name: 'eclipse', component: EclipseIcon },
	{ name: 'egg-off', component: EggOffIcon },
	{ name: 'expand', component: ExpandIcon },
	{ name: 'eye-off', component: EyeOffIcon },
	{ name: 'file-chart-column-increasing', component: FileChartColumnIncreasingIcon },
	{ name: 'file-chart-column', component: FileChartColumnIcon },
	{ name: 'file-chart-line', component: FileChartLineIcon },
	{ name: 'file-check-corner', component: FileCheckCornerIcon },
	{ name: 'file-check', component: FileCheckIcon },
	{ name: 'file-cog', component: FileCogIcon },
	{ name: 'file-down', component: FileDownIcon },
	{ name: 'file-minus', component: FileMinusIcon },
	{ name: 'file-pen-line', component: FilePenLineIcon },
	{ name: 'file-pen', component: FilePenIcon },
	{ name: 'file-plus', component: FilePlusIcon },
	{ name: 'file-question-mark', component: FileQuestionMarkIcon },
	{ name: 'file-sliders', component: FileSlidersIcon },
	{ name: 'file-stack', component: FileStackIcon },
	{ name: 'file-terminal', component: FileTerminalIcon },
	{ name: 'file-up', component: FileUpIcon },
	{ name: 'fish-off', component: FishOffIcon },
	{ name: 'flag-off', component: FlagOffIcon },
	{ name: 'flashlight-off', component: FlashlightOffIcon },
	{ name: 'flask-conical-off', component: FlaskConicalOffIcon },
	{ name: 'folder-check', component: FolderCheckIcon },
	{ name: 'folder-cog', component: FolderCogIcon },
	{ name: 'folder-down', component: FolderDownIcon },
	{ name: 'folder-kanban', component: FolderKanbanIcon },
	{ name: 'folder-pen', component: FolderPenIcon },
	{ name: 'folder-plus', component: FolderPlusIcon },
	{ name: 'folder-sync', component: FolderSyncIcon },
	{ name: 'folder-up', component: FolderUpIcon },
	{ name: 'folder-x', component: FolderXIcon },
	{ name: 'frame', component: FrameIcon },
	{ name: 'gallery-horizontal-end', component: GalleryHorizontalEndIcon },
	{ name: 'gallery-horizontal', component: GalleryHorizontalIcon },
	{ name: 'gallery-thumbnails', component: GalleryThumbnailsIcon },
	{ name: 'gallery-vertical-end', component: GalleryVerticalEndIcon },
	{ name: 'gallery-vertical', component: GalleryVerticalIcon },
	{ name: 'gauge', component: GaugeIcon },
	{ name: 'gavel', component: GavelIcon },
	{ name: 'grid-2x2-check', component: Grid2x2CheckIcon },
	{ name: 'grip-horizontal', component: GripHorizontalIcon },
	{ name: 'grip-vertical', component: GripVerticalIcon },
	{ name: 'grip', component: GripIcon },
	{ name: 'hammer', component: HammerIcon },
	{ name: 'hand-coins', component: HandCoinsIcon },
	{ name: 'hand-heart', component: HandHeartIcon },
	{ name: 'hard-drive-download', component: HardDriveDownloadIcon },
	{ name: 'hard-drive-upload', component: HardDriveUploadIcon },
	{ name: 'headphone-off', component: HeadphoneOffIcon },
	{ name: 'heart-off', component: HeartOffIcon },
	{ name: 'heart', component: HeartIcon },
	{ name: 'history', component: HistoryIcon },
	{ name: 'hop-off', component: HopOffIcon },
	{ name: 'house-wifi', component: HouseWifiIcon },
	{ name: 'house', component: HouseIcon },
	{ name: 'image-down', component: ImageDownIcon },
	{ name: 'image-off', component: ImageOffIcon },
	{ name: 'image-up', component: ImageUpIcon },
	{ name: 'images', component: ImagesIcon },
	{ name: 'infinity', component: InfinityIcon },
	{ name: 'kanban', component: KanbanIcon },
	{ name: 'key-round', component: KeyRoundIcon },
	{ name: 'key-square', component: KeySquareIcon },
	{ name: 'key', component: KeyIcon },
	{ name: 'keyboard-off', component: KeyboardOffIcon },
	{ name: 'keyboard', component: KeyboardIcon },
	{ name: 'landmark', component: LandmarkIcon },
	{ name: 'layers', component: LayersIcon },
	{ name: 'layout-dashboard', component: LayoutDashboardIcon },
	{ name: 'layout-grid', component: LayoutGridIcon },
	{ name: 'layout-panel-left', component: LayoutPanelLeftIcon },
	{ name: 'layout-panel-top', component: LayoutPanelTopIcon },
	{ name: 'layout-template', component: LayoutTemplateIcon },
	{ name: 'lightbulb-off', component: LightbulbOffIcon },
	{ name: 'lightbulb', component: LightbulbIcon },
	{ name: 'link-2-off', component: Link2OffIcon },
	{ name: 'list-check', component: ListCheckIcon },
	{ name: 'list-checks', component: ListChecksIcon },
	{ name: 'list-restart', component: ListRestartIcon },
	{ name: 'list-todo', component: ListTodoIcon },
	{ name: 'loader-pinwheel', component: LoaderPinwheelIcon },
	{ name: 'locate-off', component: LocateOffIcon },
	{ name: 'log-out', component: LogOutIcon },
	{ name: 'mail-check', component: MailCheckIcon },
	{ name: 'map-pin-check-inside', component: MapPinCheckInsideIcon },
	{ name: 'map-pin-check', component: MapPinCheckIcon },
	{ name: 'map-pin-off', component: MapPinOffIcon },
	{ name: 'maximize-2', component: Maximize2Icon },
	{ name: 'maximize', component: MaximizeIcon },
	{ name: 'megaphone-off', component: MegaphoneOffIcon },
	{ name: 'message-circle-more', component: MessageCircleMoreIcon },
	{ name: 'message-circle-off', component: MessageCircleOffIcon },
	{ name: 'message-circle-question-mark', component: MessageCircleQuestionMarkIcon },
	{ name: 'message-circle-warning', component: MessageCircleWarningIcon },
	{ name: 'message-circle', component: MessageCircleIcon },
	{ name: 'message-square-more', component: MessageSquareMoreIcon },
	{ name: 'message-square-off', component: MessageSquareOffIcon },
	{ name: 'message-square', component: MessageSquareIcon },
	{ name: 'mic-off', component: MicOffIcon },
	{ name: 'milk-off', component: MilkOffIcon },
	{ name: 'minimize-2', component: Minimize2Icon },
	{ name: 'minimize', component: MinimizeIcon },
	{ name: 'minus', component: MinusIcon },
	{ name: 'monitor-check', component: MonitorCheckIcon },
	{ name: 'monitor-cog', component: MonitorCogIcon },
	{ name: 'monitor-down', component: MonitorDownIcon },
	{ name: 'monitor-off', component: MonitorOffIcon },
	{ name: 'monitor-up', component: MonitorUpIcon },
	{ name: 'mouse-off', component: MouseOffIcon },
	{ name: 'mouse-pointer-2', component: MousePointer2Icon },
	{ name: 'mouse-pointer', component: MousePointerIcon },
	{ name: 'move-diagonal-2', component: MoveDiagonal2Icon },
	{ name: 'move-diagonal', component: MoveDiagonalIcon },
	{ name: 'move-down-left', component: MoveDownLeftIcon },
	{ name: 'move-down-right', component: MoveDownRightIcon },
	{ name: 'move-down', component: MoveDownIcon },
	{ name: 'move-horizontal', component: MoveHorizontalIcon },
	{ name: 'move-left', component: MoveLeftIcon },
	{ name: 'move-right', component: MoveRightIcon },
	{ name: 'move-up-left', component: MoveUpLeftIcon },
	{ name: 'move-up-right', component: MoveUpRightIcon },
	{ name: 'move-up', component: MoveUpIcon },
	{ name: 'move-vertical', component: MoveVerticalIcon },
	{ name: 'navigation-2-off', component: Navigation2OffIcon },
	{ name: 'navigation-off', component: NavigationOffIcon },
	{ name: 'nfc', component: NfcIcon },
	{ name: 'notebook-pen', component: NotebookPenIcon },
	{ name: 'nut-off', component: NutOffIcon },
	{ name: 'octagon-alert', component: OctagonAlertIcon },
	{ name: 'orbit', component: OrbitIcon },
	{ name: 'package-check', component: PackageCheckIcon },
	{ name: 'paintbrush', component: PaintbrushIcon },
	{ name: 'panel-bottom-close', component: PanelBottomCloseIcon },
	{ name: 'panel-bottom-open', component: PanelBottomOpenIcon },
	// { wip: true, name: 'panel-left-close', component: PanelLeftCloseIcon },
	// { wip: true, name: 'panel-left-open', component: PanelLeftOpenIcon },
	// { wip: true, name: 'panel-right-close', component: PanelRightCloseIcon },
	// { wip: true, name: 'panel-right-open', component: PanelRightOpenIcon },
	// { wip: true, name: 'panel-top-close', component: PanelTopCloseIcon },
	// { wip: true, name: 'panel-top-open', component: PanelTopOpenIcon },
	{ name: 'paperclip', component: PaperclipIcon },
	{ name: 'pen-line', component: PenLineIcon },
	{ name: 'pen-off', component: PenOffIcon },
	{ name: 'pen', component: PenIcon },
	{ name: 'pencil-line', component: PencilLineIcon },
	{ name: 'pencil-off', component: PencilOffIcon },
	{ name: 'pencil', component: PencilIcon },
	{ name: 'phone-off', component: PhoneOffIcon },
	{ name: 'pickaxe', component: PickaxeIcon },
	{ name: 'pin-off', component: PinOffIcon },
	{ name: 'plane', component: PlaneIcon },
	{ name: 'play', component: PlayIcon },
	{ name: 'plus', component: PlusIcon },
	{ name: 'pointer-off', component: PointerOffIcon },
	{ name: 'power-off', component: PowerOffIcon },
	{ name: 'printer-check', component: PrinterCheckIcon },
	{ name: 'rabbit', component: RabbitIcon },
	{ name: 'radar', component: RadarIcon },
	{ name: 'radio-tower', component: RadioTowerIcon },
	{ name: 'radio', component: RadioIcon },
	{ name: 'rainbow', component: RainbowIcon },
	{ name: 'redo-dot', component: RedoDotIcon },
	{ name: 'redo', component: RedoIcon },
	{ name: 'refresh-ccw-dot', component: RefreshCcwDotIcon },
	{ name: 'refresh-ccw', component: RefreshCcwIcon },
	{ name: 'refresh-cw-off', component: RefreshCwOffIcon },
	{ name: 'refresh-cw', component: RefreshCwIcon },
	{ name: 'rocket', component: RocketIcon },
	{ name: 'rocking-chair', component: RockingChairIcon },
	{ name: 'rotate-ccw-key', component: RotateCcwKeyIcon },
	{ name: 'rotate-ccw', component: RotateCcwIcon },
	{ name: 'rotate-cw', component: RotateCwIcon },
	{ name: 'route-off', component: RouteOffIcon },
	{ name: 'route', component: RouteIcon },
	{ name: 'rss', component: RssIcon },
	{ name: 'save-off', component: SaveOffIcon },
	{ name: 'scan-text', component: ScanTextIcon },
	{ name: 'scissors', component: ScissorsIcon },
	{ name: 'search-check', component: SearchCheckIcon },
	{ name: 'search', component: SearchIcon },
	{ name: 'send-horizontal', component: SendHorizontalIcon },
	{ name: 'send', component: SendIcon },
	{ name: 'server-cog', component: ServerCogIcon },
	{ name: 'server-off', component: ServerOffIcon },
	{ name: 'settings', component: SettingsIcon },
	{ name: 'shield-alert', component: ShieldAlertIcon },
	{ name: 'shield-check', component: ShieldCheckIcon },
	{ name: 'shield-off', component: ShieldOffIcon },
	{ name: 'shield-plus', component: ShieldPlusIcon },
	{ name: 'shield-question-mark', component: ShieldQuestionMarkIcon },
	{ name: 'ship-wheel', component: ShipWheelIcon },
	{ name: 'ship', component: ShipIcon },
	{ name: 'shopping-cart', component: ShoppingCartIcon },
	{ name: 'shovel', component: ShovelIcon },
	{ name: 'shower-head', component: ShowerHeadIcon },
	{ name: 'shrink', component: ShrinkIcon },
	{ name: 'signal-zero', component: SignalZeroIcon },
	{ name: 'signal-low', component: SignalLowIcon },
	{ name: 'signal-medium', component: SignalMediumIcon },
	{ name: 'signal-high', component: SignalHighIcon },
	{ name: 'signal', component: SignalIcon },
	{ name: 'signature', component: SignatureIcon },
	{ name: 'sliders-horizontal', component: SlidersHorizontalIcon },
	{ name: 'sliders-vertical', component: SlidersVerticalIcon },
	{ name: 'smartphone-nfc', component: SmartphoneNfcIcon },
	{ name: 'snowflake', component: SnowflakeIcon },
	{ name: 'sparkle', component: SparkleIcon },
	{ name: 'sparkles', component: SparklesIcon },
	{ name: 'speech', component: SpeechIcon },
	{ name: 'spell-check', component: SpellCheckIcon },
	{ name: 'square-arrow-down-left', component: SquareArrowDownLeftIcon },
	{ name: 'square-arrow-down-right', component: SquareArrowDownRightIcon },
	{ name: 'square-arrow-down', component: SquareArrowDownIcon },
	{ name: 'square-arrow-left', component: SquareArrowLeftIcon },
	{ name: 'square-arrow-out-down-left', component: SquareArrowOutDownLeftIcon },
	{ name: 'square-arrow-out-down-right', component: SquareArrowOutDownRightIcon },
	{ name: 'square-arrow-out-up-left', component: SquareArrowOutUpLeftIcon },
	{ name: 'square-arrow-out-up-right', component: SquareArrowOutUpRightIcon },
	{ name: 'square-arrow-right', component: SquareArrowRightIcon },
	{ name: 'square-arrow-up-left', component: SquareArrowUpLeftIcon },
	{ name: 'square-arrow-up-right', component: SquareArrowUpRightIcon },
	{ name: 'square-arrow-up', component: SquareArrowUpIcon },
	{ name: 'square-chart-gantt', component: SquareChartGanttIcon },
	{ name: 'square-check-big', component: SquareCheckBigIcon },
	{ name: 'square-check', component: SquareCheckIcon },
	{ name: 'square-chevron-down', component: SquareChevronDownIcon },
	{ name: 'square-chevron-left', component: SquareChevronLeftIcon },
	{ name: 'square-chevron-right', component: SquareChevronRightIcon },
	{ name: 'square-chevron-up', component: SquareChevronUpIcon },
	{ name: 'square-dashed-kanban', component: SquareDashedKanbanIcon },
	{ name: 'square-kanban', component: SquareKanbanIcon },
	{ name: 'square-parking-off', component: SquareParkingOffIcon },
	{ name: 'square-pen', component: SquarePenIcon },
	{ name: 'square-plus', component: SquarePlusIcon },
	{ name: 'square-scissors', component: SquareScissorsIcon },
	{ name: 'square-stack', component: SquareStackIcon },
	{ name: 'square-terminal', component: SquareTerminalIcon },
	{ name: 'star-off', component: StarOffIcon },
	{ name: 'star', component: StarIcon },
	{ name: 'sun', component: SunIcon },
	{ name: 'sword', component: SwordIcon },
	{ name: 'tag', component: TagIcon },
	{ name: 'telescope', component: TelescopeIcon },
	{ name: 'terminal', component: TerminalIcon },
	{ name: 'text-align-center', component: TextAlignCenterIcon },
	{ name: 'text-cursor-input', component: TextCursorInputIcon },
	{ name: 'text-cursor', component: TextCursorIcon },
	{ name: 'text-search', component: TextSearchIcon },
	{ name: 'thermometer', component: ThermometerIcon },
	{ name: 'thumbs-down', component: ThumbsDownIcon },
	{ name: 'thumbs-up', component: ThumbsUpIcon },
	{ name: 'ticket-check', component: TicketCheckIcon },
	{ name: 'timer-off', component: TimerOffIcon },
	{ name: 'timer', component: TimerIcon },
	{ name: 'toggle-left', component: ToggleLeftIcon },
	{ name: 'toggle-right', component: ToggleRightIcon },
	{ name: 'tornado', component: TornadoIcon },
	{ name: 'touchpad-off', component: TouchpadOffIcon },
	{ name: 'trash-2', component: Trash2Icon },
	{ name: 'trash', component: TrashIcon },
	{ name: 'triangle-alert', component: TriangleAlertIcon },
	{ name: 'umbrella-off', component: UmbrellaOffIcon },
	{ name: 'undo-dot', component: UndoDotIcon },
	{ name: 'undo', component: UndoIcon },
	{ name: 'unfold-horizontal', component: UnfoldHorizontalIcon },
	{ name: 'unfold-vertical', component: UnfoldVerticalIcon },
	{ name: 'unplug', component: UnplugIcon },
	{ name: 'upload', component: UploadIcon },
	{ name: 'user-check', component: UserCheckIcon },
	{ name: 'user-cog', component: UserCogIcon },
	{ name: 'user-pen', component: UserPenIcon },
	{ name: 'user-round-check', component: UserRoundCheckIcon },
	{ name: 'user-round-cog', component: UserRoundCogIcon },
	{ name: 'user-round-pen', component: UserRoundPenIcon },
	{ name: 'user-round', component: UserRoundIcon },
	{ name: 'user', component: UserIcon },
	{ name: 'vibrate-off', component: VibrateOffIcon },
	{ name: 'vibrate', component: VibrateIcon },
	{ name: 'video-off', component: VideoOffIcon },
	{ name: 'volume-off', component: VolumeOffIcon },
	{ name: 'vote', component: VoteIcon },
	{ name: 'waves', component: WavesIcon },
	{ name: 'webhook-off', component: WebhookOffIcon },
	{ name: 'wheat-off', component: WheatOffIcon },
	{ name: 'wifi-high', component: WifiHighIcon },
	{ name: 'wifi-low', component: WifiLowIcon },
	{ name: 'wifi-off', component: WifiOffIcon },
	{ name: 'wifi-pen', component: WifiPenIcon },
	{ name: 'wifi-zero', component: WifiZeroIcon },
	{ name: 'wifi', component: WifiIcon },
	{ name: 'wine-off', component: WineOffIcon },
	{ name: 'x', component: XIcon },
	{ name: 'zap-off', component: ZapOffIcon },
];
